-- AlterTable: add EXPIRED to visit lifecycle statuses
ALTER TABLE `visits` MODIFY `status` ENUM(
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'RESCHEDULED',
  'CANCELLED',
  'PARTIALLY_CHECKED_IN',
  'CHECKED_IN',
  'PARTIALLY_CHECKED_OUT',
  'CHECKED_OUT'
) NOT NULL DEFAULT 'PENDING_APPROVAL';

ALTER TABLE `visit_status_history` MODIFY `fromStatus` ENUM(
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'RESCHEDULED',
  'CANCELLED',
  'PARTIALLY_CHECKED_IN',
  'CHECKED_IN',
  'PARTIALLY_CHECKED_OUT',
  'CHECKED_OUT'
) NULL;

ALTER TABLE `visit_status_history` MODIFY `toStatus` ENUM(
  'PENDING_APPROVAL',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'RESCHEDULED',
  'CANCELLED',
  'PARTIALLY_CHECKED_IN',
  'CHECKED_IN',
  'PARTIALLY_CHECKED_OUT',
  'CHECKED_OUT'
) NOT NULL;
