const NATIONALITY_ENTRIES = [
   ['AF', 'Afghan'], ['AL', 'Albanian'], ['DZ', 'Algerian'], ['AS', 'American Samoan'],
   ['AD', 'Andorran'], ['AO', 'Angolan'], ['AI', 'Anguillan'], ['AQ', 'Antarctican'],
   ['AG', 'Antiguan'], ['AR', 'Argentine'], ['AM', 'Armenian'], ['AW', 'Aruban'],
   ['AU', 'Australian'], ['AT', 'Austrian'], ['AZ', 'Azerbaijani'], ['BS', 'Bahamian'],
   ['BH', 'Bahraini'], ['BD', 'Bangladeshi'], ['BB', 'Barbadian'], ['BY', 'Belarusian'],
   ['BE', 'Belgian'], ['BZ', 'Belizean'], ['BJ', 'Beninese'], ['BM', 'Bermudian'],
   ['BT', 'Bhutanese'], ['BO', 'Bolivian'], ['BQ', 'Bonairean'], ['BA', 'Bosnian'],
   ['BW', 'Botswanan'], ['BV', 'Bouvet Islander'], ['BR', 'Brazilian'], ['IO', 'British Indian Ocean Territory'],
   ['BN', 'Bruneian'], ['BG', 'Bulgarian'], ['BF', 'Burkinabe'], ['BI', 'Burundian'],
   ['CV', 'Cape Verdean'], ['KH', 'Cambodian'], ['CM', 'Cameroonian'], ['CA', 'Canadian'],
   ['KY', 'Caymanian'], ['CF', 'Central African'], ['TD', 'Chadian'], ['CL', 'Chilean'],
   ['CN', 'Chinese'], ['CX', 'Christmas Islander'], ['CC', 'Cocos Islander'], ['CO', 'Colombian'],
   ['KM', 'Comoran'], ['CG', 'Congolese'], ['CD', 'Congolese (DRC)'], ['CK', 'Cook Islander'],
   ['CR', 'Costa Rican'], ['CI', 'Ivorian'], ['HR', 'Croatian'], ['CU', 'Cuban'],
   ['CW', 'Curacaoan'], ['CY', 'Cypriot'], ['CZ', 'Czech'], ['DK', 'Danish'],
   ['DJ', 'Djiboutian'], ['DM', 'Dominican (Dominica)'], ['DO', 'Dominican (Dominican Republic)'], ['EC', 'Ecuadorian'],
   ['EG', 'Egyptian'], ['SV', 'Salvadoran'], ['GQ', 'Equatorial Guinean'], ['ER', 'Eritrean'],
   ['EE', 'Estonian'], ['SZ', 'Swazi'], ['ET', 'Ethiopian'], ['FK', 'Falkland Islander'],
   ['FO', 'Faroese'], ['FJ', 'Fijian'], ['FI', 'Finnish'], ['FR', 'French'],
   ['GF', 'French Guianese'], ['PF', 'French Polynesian'], ['TF', 'French Southern Territories'], ['GA', 'Gabonese'],
   ['GM', 'Gambian'], ['GE', 'Georgian'], ['DE', 'German'], ['GH', 'Ghanaian'],
   ['GI', 'Gibraltarian'], ['GR', 'Greek'], ['GL', 'Greenlandic'], ['GD', 'Grenadian'],
   ['GP', 'Guadeloupean'], ['GU', 'Guamanian'], ['GT', 'Guatemalan'], ['GG', 'Guernsey'],
   ['GN', 'Guinean'], ['GW', 'Bissau-Guinean'], ['GY', 'Guyanese'], ['HT', 'Haitian'],
   ['HM', 'Heard Islander'], ['VA', 'Vatican'], ['HN', 'Honduran'], ['HK', 'Hong Konger'],
   ['HU', 'Hungarian'], ['IS', 'Icelander'], ['IN', 'Indian'], ['ID', 'Indonesian'],
   ['IR', 'Iranian'], ['IQ', 'Iraqi'], ['IE', 'Irish'], ['IM', 'Manx'],
   ['IL', 'Israeli'], ['IT', 'Italian'], ['JM', 'Jamaican'], ['JP', 'Japanese'],
   ['JE', 'Jersey'], ['JO', 'Jordanian'], ['KZ', 'Kazakh'], ['KE', 'Kenyan'],
   ['KI', 'I-Kiribati'], ['KP', 'North Korean'], ['KR', 'South Korean'], ['KW', 'Kuwaiti'],
   ['KG', 'Kyrgyz'], ['LA', 'Lao'], ['LV', 'Latvian'], ['LB', 'Lebanese'],
   ['LS', 'Basotho'], ['LR', 'Liberian'], ['LY', 'Libyan'], ['LI', 'Liechtensteiner'],
   ['LT', 'Lithuanian'], ['LU', 'Luxembourgish'], ['MO', 'Macanese'], ['MG', 'Malagasy'],
   ['MW', 'Malawian'], ['MY', 'Malaysian'], ['MV', 'Maldivian'], ['ML', 'Malian'],
   ['MT', 'Maltese'], ['MH', 'Marshallese'], ['MQ', 'Martiniquais'], ['MR', 'Mauritanian'],
   ['MU', 'Mauritian'], ['YT', 'Mahoran'], ['MX', 'Mexican'], ['FM', 'Micronesian'],
   ['MD', 'Moldovan'], ['MC', 'Monacan'], ['MN', 'Mongolian'], ['ME', 'Montenegrin'],
   ['MS', 'Montserratian'], ['MA', 'Moroccan'], ['MZ', 'Mozambican'], ['MM', 'Burmese'],
   ['NA', 'Namibian'], ['NR', 'Nauruan'], ['NP', 'Nepalese'], ['NL', 'Dutch'],
   ['NC', 'New Caledonian'], ['NZ', 'New Zealander'], ['NI', 'Nicaraguan'], ['NE', 'Nigerien'],
   ['NG', 'Nigerian'], ['NU', 'Niuean'], ['NF', 'Norfolk Islander'], ['MK', 'Macedonian'],
   ['MP', 'Northern Marianan'], ['NO', 'Norwegian'], ['OM', 'Omani'], ['PK', 'Pakistani'],
   ['PW', 'Palauan'], ['PS', 'Palestinian'], ['PA', 'Panamanian'], ['PG', 'Papua New Guinean'],
   ['PY', 'Paraguayan'], ['PE', 'Peruvian'], ['PH', 'Filipino'], ['PN', 'Pitcairn Islander'],
   ['PL', 'Polish'], ['PT', 'Portuguese'], ['PR', 'Puerto Rican'], ['QA', 'Qatari'],
   ['RE', 'Reunionese'], ['RO', 'Romanian'], ['RU', 'Russian'], ['RW', 'Rwandan'],
   ['BL', 'Saint Barthelemois'], ['SH', 'Saint Helenian'], ['KN', 'Kittitian'], ['LC', 'Saint Lucian'],
   ['MF', 'Saint Martinian'], ['PM', 'Saint Pierre and Miquelonnais'], ['VC', 'Saint Vincentian'], ['WS', 'Samoan'],
   ['SM', 'Sammarinese'], ['ST', 'Sao Tomean'], ['SA', 'Saudi Arabian'], ['SN', 'Senegalese'],
   ['RS', 'Serbian'], ['SC', 'Seychellois'], ['SL', 'Sierra Leonean'], ['SG', 'Singaporean'],
   ['SX', 'Sint Maartener'], ['SK', 'Slovak'], ['SI', 'Slovenian'], ['SB', 'Solomon Islander'],
   ['SO', 'Somali'], ['ZA', 'South African'], ['GS', 'South Georgian'], ['SS', 'South Sudanese'],
   ['ES', 'Spanish'], ['LK', 'Sri Lankan'], ['SD', 'Sudanese'], ['SR', 'Surinamese'],
   ['SJ', 'Svalbardian'], ['SE', 'Swedish'], ['CH', 'Swiss'], ['SY', 'Syrian'],
   ['TW', 'Taiwanese'], ['TJ', 'Tajik'], ['TZ', 'Tanzanian'], ['TH', 'Thai'],
   ['TL', 'Timorese'], ['TG', 'Togolese'], ['TK', 'Tokelauan'], ['TO', 'Tongan'],
   ['TT', 'Trinidadian and Tobagonian'], ['TN', 'Tunisian'], ['TR', 'Turkish'], ['TM', 'Turkmen'],
   ['TC', 'Turks and Caicos Islander'], ['TV', 'Tuvaluan'], ['UG', 'Ugandan'], ['UA', 'Ukrainian'],
   ['AE', 'Emirati'], ['GB', 'British'], ['US', 'American'], ['UM', 'U.S. Minor Outlying Islands'],
   ['UY', 'Uruguayan'], ['UZ', 'Uzbek'], ['VU', 'Ni-Vanuatu'], ['VE', 'Venezuelan'],
   ['VN', 'Vietnamese'], ['VG', 'British Virgin Islander'], ['VI', 'U.S. Virgin Islander'], ['WF', 'Wallisian'],
   ['EH', 'Western Saharan'], ['YE', 'Yemeni'], ['ZM', 'Zambian'], ['ZW', 'Zimbabwean'],
] as const;

export const NATIONALITY_OPTIONS = NATIONALITY_ENTRIES.map(([value, label]) => ({
   value,
   label,
}));

export type NationalityValue = (typeof NATIONALITY_OPTIONS)[number]['value'];
export const DEFAULT_NATIONALITY = 'ET' satisfies NationalityValue;